swagger: '2.0'
info:
  description: This is a simple API
  version: 1.0.0
  title: PGi Client API
  # put the contact info for your development or API team
  contact:
    email: mark.peppers@pgi.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: internal
  description: Secured Admin-only calls
- name: external
  description: Operations available to regular developers
paths:
  /client/{id}:
    parameters:
      - in: path
        name: id
        description: Client Id
        required: true
        type: string
    get:
      tags:
        - internal
        - external
      summary: Get a Client by Id
      operationId: getClient
      description: return the requested Client
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/Client'
        404:
          description: client not found
    delete:
      tags:
        - internal
      summary: deactivate a client by Id
      operationId: deleteClient
      responses:
        200:
          description: success
        202:
          description: client already deactivated
        404:
          description: client not found
    put:
      tags:
        - internal
      summary: reactivate a Client by Id
      operationId: reactivateClient
      responses:
        200:
          description: success
        202:
          description: client already active
        404:
          description: client not found
  /client:
    post:
      tags:
        - internal
      summary: adds a Client
      operationId: addClient
      parameters:
        - in: body
          name: newClient
          description: client to add
          schema:
            $ref: '#/definitions/Client'
      responses:
        201:
          description: client created
        400:
          description: invalid input, object invalid
    put:
      tags:
        - internal
      summary: modifies a Client
      operationId: updateClient
      parameters:
        - in: body
          name: updatedClient
          description: updated client
          schema:
            $ref: '#/definitions/Client'
      responses:
        200:
          description: client updated
          schema:
            $ref: '#/definitions/Client'
        404:
          description: client not found
definitions:
  Client:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      name:
        type: string
        description: Human readable name
        example: Widget Industries NA
      startDate:
        type: string
        format: date-time
        description: Date that the client is assigned to the current license
        example: 2017-07-21T17:32:28Z
      endDate:
        type: string
        format: date-time
        description: If the client is 'deleted', the end date is set
        example: 2018-05-02T14:32:46Z
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /mpeppers/PgiClientOAPI2/1.0.0
schemes:
 - https